; overworld sprites
; SpriteSheetPointerTable indexes (see data/sprites/sprites.asm)
	const_def
	const SPRITE_NONE                    ; $00
	const SPRITE_RED                     ; $01
	const SPRITE_BLUE                    ; $02
	const SPRITE_OAK                     ; $03
	const SPRITE_YOUNGSTER               ; $04
	const SPRITE_MONSTER                 ; $05
	const SPRITE_COOLTRAINER_F           ; $06
	const SPRITE_COOLTRAINER_M           ; $07
	const SPRITE_LITTLE_GIRL             ; $08
	const SPRITE_BIRD                    ; $09
	const SPRITE_MIDDLE_AGED_MAN         ; $0a
	const SPRITE_GAMBLER                 ; $0b
	const SPRITE_SUPER_NERD              ; $0c
	const SPRITE_GIRL                    ; $0d
	const SPRITE_HIKER                   ; $0e
	const SPRITE_BEAUTY                  ; $0f
	const SPRITE_GENTLEMAN               ; $10
	const SPRITE_DAISY                   ; $11
	const SPRITE_BIKER                   ; $12
	const SPRITE_SAILOR                  ; $13
	const SPRITE_COOK                    ; $14
	const SPRITE_BIKE_SHOP_CLERK         ; $15
	const SPRITE_MR_FUJI                 ; $16
	const SPRITE_GIOVANNI                ; $17
	const SPRITE_ROCKET                  ; $18
	const SPRITE_CHANNELER               ; $19
	const SPRITE_WAITER                  ; $1a
	const SPRITE_SILPH_WORKER_F          ; $1b
	const SPRITE_MIDDLE_AGED_WOMAN       ; $1c
	const SPRITE_BRUNETTE_GIRL           ; $1d
	const SPRITE_LANCE                   ; $1e
	const SPRITE_UNUSED_SCIENTIST        ; $1f
	const SPRITE_SCIENTIST               ; $20
	const SPRITE_ROCKER                  ; $21
	const SPRITE_SWIMMER                 ; $22
	const SPRITE_SAFARI_ZONE_WORKER      ; $23
	const SPRITE_GYM_GUIDE               ; $24
	const SPRITE_GRAMPS                  ; $25
	const SPRITE_CLERK                   ; $26
	const SPRITE_FISHING_GURU            ; $27
	const SPRITE_GRANNY                  ; $28
	const SPRITE_NURSE                   ; $29
	const SPRITE_LINK_RECEPTIONIST       ; $2a
	const SPRITE_SILPH_PRESIDENT         ; $2b
	const SPRITE_SILPH_WORKER_M          ; $2c
	const SPRITE_WARDEN                  ; $2d
	const SPRITE_CAPTAIN                 ; $2e
	const SPRITE_FISHER                  ; $2f
	const SPRITE_KOGA                    ; $30
	const SPRITE_BROCK                   ; $31
	const SPRITE_MISTY                   ; $32
	const SPRITE_LT_SURGE                ; $33
	const SPRITE_ERIKA                   ; $34
	const SPRITE_SABRINA                 ; $35
	const SPRITE_BLAINE                  ; $36
	const SPRITE_GUARD                   ; $37
	const SPRITE_UNUSED_GUARD            ; $38
	const SPRITE_MOM                     ; $39
	const SPRITE_BALDING_GUY             ; $3a
	const SPRITE_LITTLE_BOY              ; $3b
	const SPRITE_UNUSED_GAMEBOY_KID      ; $3c
	const SPRITE_GAMEBOY_KID             ; $3d
	const SPRITE_FAIRY                   ; $3e
	const SPRITE_AGATHA                  ; $3f
	const SPRITE_BRUNO                   ; $40
DEF SPRITE_KAREN EQU SPRITE_BRUNO
	const SPRITE_LORELEI                 ; $41
	const SPRITE_SEEL                    ; $42
DEF FIRST_STILL_SPRITE EQU const_value
	const SPRITE_POKE_BALL               ; $43
	const SPRITE_FOSSIL                  ; $44
	const SPRITE_BOULDER                 ; $45
	const SPRITE_PAPER                   ; $46
	const SPRITE_POKEDEX                 ; $47
	const SPRITE_CLIPBOARD               ; $48
	const SPRITE_SNORLAX                 ; $49
	const SPRITE_UNUSED_OLD_AMBER        ; $4a
	const SPRITE_OLD_AMBER               ; $4b
	const SPRITE_GREEN_ROCKET            ; $4c
	const SPRITE_BLUE_CLOAK              ; $4d
	const SPRITE_UNUSED_GAMBLER_ASLEEP_2 ; $4e
	const SPRITE_GAMBLER_ASLEEP          ; $4f
	const SPRITE_NINJA                   ; $50
	const SPRITE_JANINE                  ; $51
	const SPRITE_MEW                     ; $52
	const SPRITE_ARIANA                 ; $53
	const SPRITE_ARCHER                 ; $54
	const SPRITE_PETREL                 ; $55
	const SPRITE_PROTON                 ; $56
	const SPRITE_SOLDIER                ; $57
	const SPRITE_BULBASAUR              ; $58
	const SPRITE_CHARMANDER             ; $59
	const SPRITE_SQUIRTLE               ; $5a
	const SPRITE_CHIKORITA              ; $5b
	const SPRITE_CYNDAQUIL              ; $5c
	const SPRITE_TOTODILE               ; $5d
	const SPRITE_PIDGEY                 ; $5e
	const SPRITE_SPEAROW                ; $5f
	const SPRITE_FEAROW                 ; $60
	const SPRITE_DODUO                  ; $61
	const SPRITE_PIDGEOT                ; $62
	const SPRITE_CHANSEY                ; $63
	const SPRITE_PIKACHU                ; $64
	const SPRITE_LAPRAS                 ; $65
	const SPRITE_MACHOP                 ; $66
	const SPRITE_MACHOKE                ; $67
	const SPRITE_POLIWRATH              ; $68
	const SPRITE_CUBONE                 ; $69
	const SPRITE_MEWTWO                 ; $6a
	const SPRITE_MEOWTH                 ; $6b
	const SPRITE_NIDORAN_F              ; $6c
	const SPRITE_NIDORAN_M              ; $6d
	const SPRITE_NIDORINO               ; $6e
	const SPRITE_PSYDUCK                ; $6f
	const SPRITE_CLEFAIRY               ; $70
	const SPRITE_JIGGLYPUFF             ; $71
	const SPRITE_WIGGLYTUFF             ; $72
	const SPRITE_KANGASKHAN             ; $73
	const SPRITE_SLOWPOKE               ; $74
	const SPRITE_SLOWBRO                ; $75
	const SPRITE_VOLTORB                ; $76
	const SPRITE_ELECTRODE              ; $77
	const SPRITE_ARTICUNO               ; $78
	const SPRITE_ZAPDOS                 ; $79
	const SPRITE_MOLTRES                ; $7a
	const SPRITE_YOUNGSTER_NEW          ; $7b
	const SPRITE_BUG_CATCHER_NEW        ; $7c
	const SPRITE_LASS_NEW               ; $7d
	const SPRITE_JR_TRAINER_M_NEW       ; $7e
	const SPRITE_JR_TRAINER_F_NEW       ; $7f
	const SPRITE_POKEMANIAC_NEW         ; $80
	const SPRITE_SUPER_NERD_NEW         ; $81
	const SPRITE_HIKER_NEW              ; $82
	const SPRITE_BURGLAR_NEW            ; $83
	const SPRITE_ENGINEER_NEW           ; $84
	const SPRITE_FISHER_NEW             ; $85
	const SPRITE_SWIMMER_NEW            ; $86
	const SPRITE_CUE_BALL_NEW           ; $87
	const SPRITE_ROCKER_NEW             ; $88
	const SPRITE_JUGGLER_NEW            ; $89
	const SPRITE_TAMER_NEW              ; $8a
	const SPRITE_BIRD_KEEPER_NEW        ; $8b
	const SPRITE_BLACKBELT_NEW          ; $8c
	const SPRITE_SWIMMER_F              ; $8d
DEF NUM_SPRITES EQU const_value - 1
