SECTION "NPC Sprites 1", ROMX

ScientistSprite::        INCBIN "gfx/sprites/scientist.2bpp"
RockerSprite::           INCBIN "gfx/sprites/rocker.2bpp"
SwimmerSprite::          INCBIN "gfx/sprites/swimmer.2bpp"
SafariZoneWorkerSprite:: INCBIN "gfx/sprites/safari_zone_worker.2bpp"
GymGuideSprite::         INCBIN "gfx/sprites/gym_guide.2bpp"
GrampsSprite::           INCBIN "gfx/sprites/gramps.2bpp"
ClerkSprite::            INCBIN "gfx/sprites/clerk.2bpp"
FishingGuruSprite::      INCBIN "gfx/sprites/fishing_guru.2bpp"
GrannySprite::           INCBIN "gfx/sprites/granny.2bpp"
NurseSprite::            INCBIN "gfx/sprites/nurse.2bpp"
LinkReceptionistSprite:: INCBIN "gfx/sprites/link_receptionist.2bpp"
SilphPresidentSprite::   INCBIN "gfx/sprites/silph_president.2bpp"
SilphWorkerMSprite::     INCBIN "gfx/sprites/silph_worker_m.2bpp"
WardenSprite::           INCBIN "gfx/sprites/warden.2bpp"
CaptainSprite::          INCBIN "gfx/sprites/captain.2bpp"
FisherSprite::           INCBIN "gfx/sprites/fisher.2bpp"
PokeBallSprite::         INCBIN "gfx/sprites/poke_ball.2bpp"
FossilSprite::           INCBIN "gfx/sprites/fossil.2bpp"
BoulderSprite::          INCBIN "gfx/sprites/boulder.2bpp"
PaperSprite::            INCBIN "gfx/sprites/paper.2bpp"
PokedexSprite::          INCBIN "gfx/sprites/pokedex.2bpp"
ClipboardSprite::        INCBIN "gfx/sprites/clipboard.2bpp"
SnorlaxSprite::          INCBIN "gfx/icons/snorlax_ow.2bpp"
OldAmberSprite::         INCBIN "gfx/sprites/old_amber.2bpp"
GamblerAsleepSprite::    INCBIN "gfx/sprites/gambler_asleep.2bpp"
MewSprite::              INCBIN "gfx/icons/mew_ow.2bpp"
BulbasaurSprite::        INCBIN "gfx/sprites/bulbasaur.2bpp"
CharmanderSprite::       INCBIN "gfx/icons/charmander_ow.2bpp"
SquirtleSprite::         INCBIN "gfx/icons/squirtle_ow.2bpp"
ChikoritaSprite::        INCBIN "gfx/icons/chikorita.2bpp"
CyndaquilSprite::        INCBIN "gfx/icons/cyndaquil.2bpp"
TotodileSprite::         INCBIN "gfx/icons/totodile.2bpp"


SECTION "NPC Sprites 2", ROMX

RedBikeSprite::          INCBIN "gfx/sprites/red_bike.2bpp"
RedSkateboardSprite::    INCBIN "gfx/sprites/red_skateboard.2bpp"
RedSprite::              INCBIN "gfx/sprites/red.2bpp"
BlueSprite::             INCBIN "gfx/sprites/blue.2bpp"
OakSprite::              INCBIN "gfx/sprites/oak.2bpp"
YoungsterSprite::        INCBIN "gfx/sprites/youngster.2bpp"
MonsterSprite::          INCBIN "gfx/sprites/monster.2bpp"
CooltrainerFSprite::     INCBIN "gfx/sprites/cooltrainer_f.2bpp"
CooltrainerMSprite::     INCBIN "gfx/sprites/cooltrainer_m.2bpp"
LittleGirlSprite::       INCBIN "gfx/sprites/little_girl.2bpp"
BirdSprite::             INCBIN "gfx/sprites/bird.2bpp"
MiddleAgedManSprite::    INCBIN "gfx/sprites/middle_aged_man.2bpp"
GamblerSprite::          INCBIN "gfx/sprites/gambler.2bpp"
SuperNerdSprite::        INCBIN "gfx/sprites/super_nerd.2bpp"
GirlSprite::             INCBIN "gfx/sprites/girl.2bpp"
HikerSprite::            INCBIN "gfx/sprites/hiker.2bpp"
BeautySprite::           INCBIN "gfx/sprites/beauty.2bpp"
GentlemanSprite::        INCBIN "gfx/sprites/gentleman.2bpp"
DaisySprite::            INCBIN "gfx/sprites/daisy.2bpp"
BikerSprite::            INCBIN "gfx/sprites/biker.2bpp"
SailorSprite::           INCBIN "gfx/sprites/sailor.2bpp"
CookSprite::             INCBIN "gfx/sprites/cook.2bpp"
BikeShopClerkSprite::    INCBIN "gfx/sprites/bike_shop_clerk.2bpp"
MrFujiSprite::           INCBIN "gfx/sprites/mr_fuji.2bpp"
GiovanniSprite::         INCBIN "gfx/sprites/giovanni.2bpp"
RocketSprite::           INCBIN "gfx/sprites/rocket.2bpp"
ChannelerSprite::        INCBIN "gfx/sprites/channeler.2bpp"
WaiterSprite::           INCBIN "gfx/sprites/waiter.2bpp"
SilphWorkerFSprite::     INCBIN "gfx/sprites/silph_worker_f.2bpp"
MiddleAgedWomanSprite::  INCBIN "gfx/sprites/middle_aged_woman.2bpp"
BrunetteGirlSprite::     INCBIN "gfx/sprites/brunette_girl.2bpp"
LanceSprite::            INCBIN "gfx/sprites/lance.2bpp"
MomSprite::              INCBIN "gfx/sprites/mom.2bpp"
BaldingGuySprite::       INCBIN "gfx/sprites/balding_guy.2bpp"
LittleBoySprite::        INCBIN "gfx/sprites/little_boy.2bpp"
GameboyKidSprite::       INCBIN "gfx/sprites/gameboy_kid.2bpp"
FairySprite::            INCBIN "gfx/sprites/fairy.2bpp"
AgathaSprite::           INCBIN "gfx/sprites/agatha.2bpp"
IF !DEF(_RED)
KarenSprite::            INCBIN "gfx/sprites/karen.2bpp"
ENDC
LoreleiSprite::          INCBIN "gfx/sprites/lorelei.2bpp"


SECTION "Gym Leader OW Sprites", ROMX

BrockSprite::            INCBIN "gfx/sprites/brock.2bpp"
MistySprite::            INCBIN "gfx/sprites/misty.2bpp"
LtSurgeSprite::          INCBIN "gfx/sprites/surge.2bpp"
ErikaSprite::            INCBIN "gfx/sprites/erika.2bpp"
SabrinaSprite::          INCBIN "gfx/sprites/sabrina.2bpp"
BlaineSprite::           INCBIN "gfx/sprites/blaine.2bpp"


; Bank 4 (with NPC Sprites 1 + Font + Battle Engine 1) is full — same pattern as
; Blue Cloak. These 12-tile sheets (~1.5KB) live in a spare slot in bank 1.
SECTION "Koga Guard and Admin OW Sprites", ROMX

KogaSprite::             INCBIN "gfx/sprites/koga.2bpp"
GuardSprite::            INCBIN "gfx/sprites/guard.2bpp"
NinjaSprite::            INCBIN "gfx/sprites/ninja.2bpp"
JanineSprite::           INCBIN "gfx/sprites/janine.2bpp"


SECTION "Rocket Admin OW Sprites", ROMX

ArianaSprite::           INCBIN "gfx/sprites/ariana.2bpp"
ArcherSprite::            INCBIN "gfx/sprites/archer.2bpp"
PetrelSprite::            INCBIN "gfx/sprites/petrel.2bpp"
ProtonSprite::            INCBIN "gfx/sprites/proton.2bpp"
SoldierSprite::           INCBIN "gfx/sprites/soldier.2bpp"
RocketGirlSprite::        INCBIN "gfx/sprites/rocket_girl.2bpp"


; Keep the larger Pokemon-specific overworld sheets outside the cramped legacy NPC
; banks so the linker can place them in roomier ROMX space without disturbing the
; original sprite ordering.
SECTION "Pokemon OW Sprites 1", ROMX

PidgeySprite::           INCBIN "gfx/sprites/pidgey.2bpp"
SpearowSprite::          INCBIN "gfx/sprites/spearow.2bpp"
FearowSprite::           INCBIN "gfx/sprites/fearow.2bpp"
DoduoSprite::            INCBIN "gfx/sprites/doduo.2bpp"
PidgeotSprite::          INCBIN "gfx/sprites/pidgeot.2bpp"
ChanseySprite::          INCBIN "gfx/sprites/chansey.2bpp"
PikachuSprite::          INCBIN "gfx/sprites/pikachu.2bpp"
LaprasSprite::           INCBIN "gfx/sprites/lapras.2bpp"

SECTION "Pokemon OW Sprites 2", ROMX

MachopSprite::           INCBIN "gfx/sprites/machop.2bpp"
MachokeSprite::          INCBIN "gfx/sprites/machoke.2bpp"
PoliwrathSprite::        INCBIN "gfx/sprites/poliwrath.2bpp"
CuboneSprite::           INCBIN "gfx/sprites/cubone.2bpp"
MewtwoSprite::           INCBIN "gfx/sprites/mewtwo.2bpp"
MeowthSprite::           INCBIN "gfx/sprites/meowth.2bpp"
NidoranFSprite::         INCBIN "gfx/sprites/nidoranf.2bpp"
NidoranMSprite::         INCBIN "gfx/sprites/nidoranm.2bpp"
NidorinoSprite::         INCBIN "gfx/sprites/nidorino.2bpp"
PsyduckSprite::          INCBIN "gfx/sprites/psyduck.2bpp"

SECTION "Pokemon OW Sprites 3", ROMX

ClefairySprite::         INCBIN "gfx/sprites/clefairy.2bpp"
JigglypuffSprite::       INCBIN "gfx/sprites/jigglypuff.2bpp"
WigglytuffSprite::       INCBIN "gfx/sprites/wigglytuff.2bpp"
KangaskhanSprite::       INCBIN "gfx/sprites/kangaskhan.2bpp"
SlowpokeSprite::         INCBIN "gfx/sprites/slowpoke.2bpp"
ArticunoSprite::         INCBIN "gfx/sprites/articuno.2bpp"
ZapdosSprite::           INCBIN "gfx/sprites/zapdos.2bpp"
MoltresSprite::          INCBIN "gfx/sprites/moltres.2bpp"

SECTION "Pokemon OW Sprites 4", ROMX

SlowbroSprite::          INCBIN "gfx/icons/slowbro_ow.2bpp"
VoltorbSprite::          INCBIN "gfx/icons/voltorb_ow.2bpp"
ElectrodeSprite::        INCBIN "gfx/icons/electrode_ow.2bpp"


; Keep this 12-tile sheet in overflow space; the sprite pointer table records its bank.
SECTION "Blue Cloak OW Sprite", ROMX

BlueCloakWorldSprite::   INCBIN "gfx/sprites/blue_cloak_world.2bpp"

IF DEF(_RED)
; Red uses Bruno in the shared Bruno/Karen slot. Keep his larger source sheet out of
; the cramped legacy NPC bank; the sprite pointer table already tracks the bank.
SECTION "Bruno OW Sprite", ROMX

KarenSprite::            INCBIN "gfx/sprites/bruno.2bpp"
ENDC

IF DEF(_BLUE)
SECTION "Exile Bruno OW Sprite", ROMX

ExileBrunoSprite::        INCBIN "gfx/sprites/brunoblindfold.2bpp"
ENDC


SECTION "NPC Sprites 2 Overflow", ROMX

SeelSprite::             INCBIN "gfx/sprites/seel.2bpp"
RocketAsleepSprite::     INCBIN "gfx/sprites/rocket_asleep.2bpp"


SECTION "Trainer Class OW Sprites 1", ROMX

YoungsterNewSprite::     INCBIN "gfx/sprites/youngster_new.2bpp"
BugCatcherNewSprite::    INCBIN "gfx/sprites/bug_catcher_new.2bpp"
LassNewSprite::          INCBIN "gfx/sprites/lass_new.2bpp"
JrTrainerMNewSprite::    INCBIN "gfx/sprites/jr_trainer_m_new.2bpp"
JrTrainerFNewSprite::    INCBIN "gfx/sprites/jr_trainer_f_new.2bpp"
PokemaniacNewSprite::    INCBIN "gfx/sprites/pokemaniac_new.2bpp"
SuperNerdNewSprite::     INCBIN "gfx/sprites/super_nerd_new.2bpp"
HikerNewSprite::         INCBIN "gfx/sprites/hiker_new.2bpp"
BurglarNewSprite::       INCBIN "gfx/sprites/burglar_new.2bpp"

SECTION "Trainer Class OW Sprites 2", ROMX

EngineerNewSprite::      INCBIN "gfx/sprites/engineer_new.2bpp"
FisherNewSprite::        INCBIN "gfx/sprites/fisher_new.2bpp"
SwimmerNewSprite::       INCBIN "gfx/sprites/swimmer_new.2bpp"
SwimmerFSprite::         INCBIN "gfx/sprites/swimmerf.2bpp"
CueBallNewSprite::       INCBIN "gfx/sprites/cue_ball_new.2bpp"
RockerNewSprite::        INCBIN "gfx/sprites/rocker_new.2bpp"
JugglerNewSprite::       INCBIN "gfx/sprites/juggler_new.2bpp"
TamerNewSprite::         INCBIN "gfx/sprites/tamer_new.2bpp"
BirdKeeperNewSprite::    INCBIN "gfx/sprites/bird_keeper_new.2bpp"
BlackbeltNewSprite::     INCBIN "gfx/sprites/blackbelt_new.2bpp"
BeautyNewSprite::        INCBIN "gfx/sprites/beauty_new.2bpp"


SECTION "Mon Icons 1", ROMX

MonIcons::
INCBIN "gfx/icons/null.2bpp"
INCBIN "gfx/icons/bulbasaur.2bpp"
INCBIN "gfx/icons/ivysaur.2bpp"
INCBIN "gfx/icons/venusaur.2bpp"
INCBIN "gfx/icons/charmander.2bpp"
INCBIN "gfx/icons/charmeleon.2bpp"
INCBIN "gfx/icons/charizard.2bpp"
INCBIN "gfx/icons/squirtle.2bpp"
INCBIN "gfx/icons/wartortle.2bpp"
INCBIN "gfx/icons/blastoise.2bpp"
INCBIN "gfx/icons/caterpie.2bpp"
INCBIN "gfx/icons/metapod.2bpp"
INCBIN "gfx/icons/butterfree.2bpp"
INCBIN "gfx/icons/weedle.2bpp"
INCBIN "gfx/icons/kakuna.2bpp"
INCBIN "gfx/icons/beedrill.2bpp"
INCBIN "gfx/icons/pidgey.2bpp"
INCBIN "gfx/icons/pidgeotto.2bpp"
INCBIN "gfx/icons/pidgeot.2bpp"
INCBIN "gfx/icons/rattata.2bpp"
INCBIN "gfx/icons/raticate.2bpp"
INCBIN "gfx/icons/spearow.2bpp"
INCBIN "gfx/icons/fearow.2bpp"
INCBIN "gfx/icons/ekans.2bpp"
INCBIN "gfx/icons/arbok.2bpp"
INCBIN "gfx/icons/pikachu.2bpp"
INCBIN "gfx/icons/raichu.2bpp"
INCBIN "gfx/icons/sandshrew.2bpp"
INCBIN "gfx/icons/sandslash.2bpp"
INCBIN "gfx/icons/nidoran_f.2bpp"
INCBIN "gfx/icons/nidorina.2bpp"
INCBIN "gfx/icons/nidoqueen.2bpp"
INCBIN "gfx/icons/nidoran_m.2bpp"
INCBIN "gfx/icons/nidorino.2bpp"
INCBIN "gfx/icons/nidoking.2bpp"
INCBIN "gfx/icons/clefairy.2bpp"
INCBIN "gfx/icons/clefable.2bpp"
INCBIN "gfx/icons/vulpix.2bpp"
INCBIN "gfx/icons/ninetales.2bpp"
INCBIN "gfx/icons/jigglypuff.2bpp"
INCBIN "gfx/icons/wigglytuff.2bpp"
INCBIN "gfx/icons/zubat.2bpp"
INCBIN "gfx/icons/golbat.2bpp"
INCBIN "gfx/icons/oddish.2bpp"
INCBIN "gfx/icons/gloom.2bpp"
INCBIN "gfx/icons/vileplume.2bpp"
INCBIN "gfx/icons/paras.2bpp"
INCBIN "gfx/icons/parasect.2bpp"
INCBIN "gfx/icons/venonat.2bpp"
INCBIN "gfx/icons/venomoth.2bpp"
INCBIN "gfx/icons/diglett.2bpp"
INCBIN "gfx/icons/dugtrio.2bpp"
INCBIN "gfx/icons/meowth.2bpp"
INCBIN "gfx/icons/persian.2bpp"
INCBIN "gfx/icons/psyduck.2bpp"
INCBIN "gfx/icons/golduck.2bpp"
INCBIN "gfx/icons/mankey.2bpp"
INCBIN "gfx/icons/primeape.2bpp"
INCBIN "gfx/icons/growlithe.2bpp"
INCBIN "gfx/icons/arcanine.2bpp"
INCBIN "gfx/icons/poliwag.2bpp"
INCBIN "gfx/icons/poliwhirl.2bpp"
INCBIN "gfx/icons/poliwrath.2bpp"
INCBIN "gfx/icons/abra.2bpp"
INCBIN "gfx/icons/kadabra.2bpp"
INCBIN "gfx/icons/alakazam.2bpp"
INCBIN "gfx/icons/machop.2bpp"
INCBIN "gfx/icons/machoke.2bpp"
INCBIN "gfx/icons/machamp.2bpp"
INCBIN "gfx/icons/bellsprout.2bpp"
INCBIN "gfx/icons/weepinbell.2bpp"
INCBIN "gfx/icons/victreebel.2bpp"
INCBIN "gfx/icons/tentacool.2bpp"
INCBIN "gfx/icons/tentacruel.2bpp"
INCBIN "gfx/icons/geodude.2bpp"
INCBIN "gfx/icons/graveler.2bpp"
INCBIN "gfx/icons/golem.2bpp"
INCBIN "gfx/icons/ponyta.2bpp"
INCBIN "gfx/icons/rapidash.2bpp"
INCBIN "gfx/icons/slowpoke.2bpp"
INCBIN "gfx/icons/slowbro.2bpp"
INCBIN "gfx/icons/magnemite.2bpp"
INCBIN "gfx/icons/magneton.2bpp"
INCBIN "gfx/icons/farfetchd.2bpp"
INCBIN "gfx/icons/doduo.2bpp"
INCBIN "gfx/icons/dodrio.2bpp"
INCBIN "gfx/icons/seel.2bpp"
INCBIN "gfx/icons/dewgong.2bpp"
INCBIN "gfx/icons/grimer.2bpp"
INCBIN "gfx/icons/muk.2bpp"
INCBIN "gfx/icons/shellder.2bpp"
INCBIN "gfx/icons/cloyster.2bpp"
INCBIN "gfx/icons/gastly.2bpp"
INCBIN "gfx/icons/haunter.2bpp"
INCBIN "gfx/icons/gengar.2bpp"
INCBIN "gfx/icons/onix.2bpp"
INCBIN "gfx/icons/drowzee.2bpp"
INCBIN "gfx/icons/hypno.2bpp"
INCBIN "gfx/icons/krabby.2bpp"
INCBIN "gfx/icons/kingler.2bpp"
INCBIN "gfx/icons/voltorb.2bpp"
INCBIN "gfx/icons/electrode.2bpp"
INCBIN "gfx/icons/exeggcute.2bpp"
INCBIN "gfx/icons/exeggutor.2bpp"
INCBIN "gfx/icons/cubone.2bpp"
INCBIN "gfx/icons/marowak.2bpp"
INCBIN "gfx/icons/hitmonlee.2bpp"
INCBIN "gfx/icons/hitmonchan.2bpp"
INCBIN "gfx/icons/lickitung.2bpp"
INCBIN "gfx/icons/koffing.2bpp"
INCBIN "gfx/icons/weezing.2bpp"
INCBIN "gfx/icons/rhyhorn.2bpp"
INCBIN "gfx/icons/rhydon.2bpp"
INCBIN "gfx/icons/chansey.2bpp"
INCBIN "gfx/icons/tangela.2bpp"
INCBIN "gfx/icons/kangaskhan.2bpp"
INCBIN "gfx/icons/horsea.2bpp"
INCBIN "gfx/icons/seadra.2bpp"
INCBIN "gfx/icons/goldeen.2bpp"
INCBIN "gfx/icons/seaking.2bpp"
INCBIN "gfx/icons/staryu.2bpp"
INCBIN "gfx/icons/starmie.2bpp"
INCBIN "gfx/icons/mr_mime.2bpp"
INCBIN "gfx/icons/scyther.2bpp"
INCBIN "gfx/icons/jynx.2bpp"
INCBIN "gfx/icons/electabuzz.2bpp"
INCBIN "gfx/icons/magmar.2bpp"
INCBIN "gfx/icons/pinsir.2bpp"


SECTION "Mon Icons 2", ROMX

MonIcons2::
INCBIN "gfx/icons/tauros.2bpp"
INCBIN "gfx/icons/magikarp.2bpp"
INCBIN "gfx/icons/gyarados.2bpp"
INCBIN "gfx/icons/lapras.2bpp"
INCBIN "gfx/icons/ditto.2bpp"
INCBIN "gfx/icons/eevee.2bpp"
INCBIN "gfx/icons/vaporeon.2bpp"
INCBIN "gfx/icons/jolteon.2bpp"
INCBIN "gfx/icons/flareon.2bpp"
INCBIN "gfx/icons/porygon.2bpp"
INCBIN "gfx/icons/omanyte.2bpp"
INCBIN "gfx/icons/omastar.2bpp"
INCBIN "gfx/icons/kabuto.2bpp"
INCBIN "gfx/icons/kabutops.2bpp"
INCBIN "gfx/icons/aerodactyl.2bpp"
INCBIN "gfx/icons/snorlax.2bpp"
INCBIN "gfx/icons/articuno.2bpp"
INCBIN "gfx/icons/zapdos.2bpp"
INCBIN "gfx/icons/moltres.2bpp"
INCBIN "gfx/icons/dratini.2bpp"
INCBIN "gfx/icons/dragonair.2bpp"
INCBIN "gfx/icons/dragonite.2bpp"
INCBIN "gfx/icons/mewtwo.2bpp"
INCBIN "gfx/icons/mew.2bpp"
INCBIN "gfx/icons/chikorita.2bpp"
INCBIN "gfx/icons/bayleef.2bpp"
INCBIN "gfx/icons/meganium.2bpp"
INCBIN "gfx/icons/cyndaquil.2bpp"
INCBIN "gfx/icons/quilava.2bpp"
INCBIN "gfx/icons/typhlosion.2bpp"
INCBIN "gfx/icons/totodile.2bpp"
INCBIN "gfx/icons/croconaw.2bpp"
INCBIN "gfx/icons/feraligatr.2bpp"
INCBIN "gfx/icons/murkrow.2bpp"
INCBIN "gfx/icons/honchkrow.2bpp"
INCBIN "gfx/icons/misdreavus.2bpp"
INCBIN "gfx/icons/mismagius.2bpp"
INCBIN "gfx/icons/guardia.2bpp"
INCBIN "gfx/icons/masquawk.2bpp"
INCBIN "gfx/icons/gorochu.2bpp"
INCBIN "gfx/icons/larvitar.2bpp"
INCBIN "gfx/icons/pupitar.2bpp"
INCBIN "gfx/icons/tyranitar.2bpp"
INCBIN "gfx/icons/ralts.2bpp"
INCBIN "gfx/icons/kirlia.2bpp"
INCBIN "gfx/icons/gardevoir.2bpp"
INCBIN "gfx/icons/riolu.2bpp"
INCBIN "gfx/icons/lucario.2bpp"
INCBIN "gfx/icons/bagon.2bpp"
INCBIN "gfx/icons/shelgon.2bpp"
INCBIN "gfx/icons/salamence.2bpp"
INCBIN "gfx/icons/duskull.2bpp"
INCBIN "gfx/icons/dusclops.2bpp"
INCBIN "gfx/icons/dusknoir.2bpp"
INCBIN "gfx/icons/golett.2bpp"
INCBIN "gfx/icons/golurk.2bpp"
INCBIN "gfx/icons/heracross.2bpp"
INCBIN "gfx/icons/espeon.2bpp"
INCBIN "gfx/icons/umbreon.2bpp"
INCBIN "gfx/icons/glaceon.2bpp"
INCBIN "gfx/icons/leafeon.2bpp"
INCBIN "gfx/icons/annihilape.2bpp"
INCBIN "gfx/icons/blissey.2bpp"
INCBIN "gfx/icons/crobat.2bpp"
INCBIN "gfx/icons/electivire.2bpp"
INCBIN "gfx/icons/kingdra.2bpp"
INCBIN "gfx/icons/lickilicky.2bpp"
INCBIN "gfx/icons/magmortar.2bpp"
INCBIN "gfx/icons/magnezone.2bpp"
INCBIN "gfx/icons/porygon2.2bpp"
INCBIN "gfx/icons/porygon_z.2bpp"
INCBIN "gfx/icons/rhyperior.2bpp"
INCBIN "gfx/icons/scizor.2bpp"
INCBIN "gfx/icons/steelix.2bpp"
INCBIN "gfx/icons/tangrowth.2bpp"
INCBIN "gfx/icons/venipede.2bpp"
INCBIN "gfx/icons/whirlipede.2bpp"
INCBIN "gfx/icons/scolipede.2bpp"
INCBIN "gfx/icons/sneasel.2bpp"
INCBIN "gfx/icons/weavile.2bpp"
INCBIN "gfx/icons/mesmeria.2bpp"
INCBIN "gfx/icons/croagunk.2bpp"
INCBIN "gfx/icons/toxicroak.2bpp"
INCBIN "gfx/icons/phanpy.2bpp"
INCBIN "gfx/icons/donphan.2bpp"
INCBIN "gfx/icons/houndour.2bpp"
INCBIN "gfx/icons/houndoom.2bpp"
INCBIN "gfx/icons/cranidos.2bpp"
INCBIN "gfx/icons/rampardos.2bpp"
INCBIN "gfx/icons/shieldon.2bpp"
INCBIN "gfx/icons/bastiodon.2bpp"
INCBIN "gfx/icons/buneary.2bpp"
INCBIN "gfx/icons/lopunny.2bpp"
INCBIN "gfx/icons/wimpod.2bpp"
INCBIN "gfx/icons/golisopod.2bpp"
INCBIN "gfx/icons/lileep.2bpp"
INCBIN "gfx/icons/cradily.2bpp"
INCBIN "gfx/icons/anorith.2bpp"
INCBIN "gfx/icons/armaldo.2bpp"
INCBIN "gfx/icons/cufant.2bpp"
INCBIN "gfx/icons/copperajah.2bpp"
INCBIN "gfx/icons/toxel.2bpp"
INCBIN "gfx/icons/toxtricity.2bpp"
