_CeruleanBadgeHouseFossilScientistIntroText::
	text "Hello there! I"
	cont "used to"
	cont "work at the"
	cont "Cinnabar Lab!"
	cont "I split off from"
	cont "the rest of them"
	cont "since we had"
	cont "very different"
	cont "opinions. Im"
	cont "more than"
	cont "capable of"
	cont "reviving fossils"
	cont "just as well in"
	cont "my homemade lab"
	cont "here, do you have"
	cont "any?"
	done
